spring:
  application:
    name: 11-spring-boot-Runners-runner-app


# Field Injection
emp:
  info:
    eid: 10
    ename: sachin
    eaddress: MI

std:
  info:
    sid: 18
    sname: dravid
    saddress: RCB